secret:
    databaseUrl: ENC[AES256_GCM,data:xtqmu4rU66ZAY7XGEdsRp2irYFA06VT7vUoULzHsaRAGxc6qE7gjy4GTAjGZCWYwYueX7tvIy9VVTedqPr5PCJr1pqW9qxmY8GmuvdrKLg9hP/zAiZ471jgIsrr2mVch3srKi2UtiDL2h67F,iv:N9wNeYWYDURL3Na9kGuJ/siNkwof6twpxonOTHTOaoA=,tag:tlDrA2pi/Axl16Q88ov8IA==,type:str]
sops:
    age:
        - recipient: age1dwzvf8mj4rgvacakeecghshlyqkv873e70azfhpstvzpfj9v0uws8eqgwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRkFRQitqbjBuZWdpNTFQ
            SS9veTAyNnJ2by9rWG44WkQzSzlJZUFzRVc0CmVqWGhWb1pGbmk5RjNMTWlXVmpz
            TWwxdjJjNzB6dVVKZUtDZ2xpU2VESU0KLS0tIElYRE12MW1ydS9Zc29xZXU2a24r
            bGNKZ1RUdWg3TGFXMGxma3NUbllSM0UK3rQdUl95Tm9YmUiuauw2e4IXVkRIao++
            gAy2t4mNYky4CRpPYUFabJrg69OosueBNhJiQ9CuRiM8H1lyz7jT3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T00:50:54Z"
    mac: ENC[AES256_GCM,data:1qoubtKhB2uiYHbJF3w33BEEqtKcqbPKwzXGo5RAEzuS0hilWkZKXpW3TPeLCs6PmJcZzMMIGuy5kOb1DkJKcJ7VD0y367g7xA+UMHtizKYdM92dyIvBlJOAcoDK2+PRATf8vDvsYKOyb3CKZpkNXe+yem3ptlZvYFD3foLZk4Y=,iv:xjQQOEUyVJNw57PGFSLYmn13Xa3fxa8/QNaJ4Nj9nbA=,tag:5nvlULxWsW0rL/27a5mIpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
