secret:
    databaseUrl: ENC[AES256_GCM,data:LlH1mNzVBkK20LCNzI1LQDbMb3ajMXmFdWNbobJVm/JYp53bG13zwQYzbDeVpluYpEifHPDzXqd0C1gimszio6kSFrqw8TFOEeV8kdDcAW11OdudYtbcJz8=,iv:yOV8QYvkkWIAMQp9lxMmRzUp3VlLgtnP14Yo+Ptuirc=,tag:5Z0Y/1txE2bKadXzp6Ny3Q==,type:str]
sops:
    age:
        - recipient: age1a4f6hu2ly5mkda56jj8juep8w4mzluw2mc70ek5evkqvdztenyjqm7cykc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R05McnM1djFBRDYwZ2Ez
            TVBMOGh0OHB3blI3K3JzRFB2emJDT3R6bmtvCmFCRUVZbzg4WWJWcjRrbk5tUkp1
            S0xoVG9LMTJSUjdKallFYXJud1I5OE0KLS0tIGJGbmFpR3lWTFhuTkdFc2R1R2Ro
            M282SHFMMWpENXZSZ0s0TUdIeVZmV3MK7dQD/i3XGIuvFKz8vJfLnB5KxnJAY60k
            Bn7qprdIoB9I7skdPD4vxS8QeENru8Q12+7zBXFalY6gAC7DXnMZ+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T05:20:24Z"
    mac: ENC[AES256_GCM,data:oC8kIGlqSEu+UAbCsK9g0hUL4Zj1pxfUU8AgHP5YN9AkWw5lRceLKDXmgjm7gM832rGwXtlMd7LetFYGGfibRRiVf1mwmR2hzWrGsFFXenk50jBZYjqANfW4S/N0ylhbU9EXx9l9ix1D9sJDo0Hsc0Ng3D9n28zL/S67mvUJE1M=,iv:ZcRpnLe8D5Y5D6zbZ0+UK6vg+7WIIklQjyMwF0h6ChY=,tag:VZZ9Hpm5LIfR6tCLsAV3LA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
