secret:
    dbName: ENC[AES256_GCM,data:U6LmR7bQIWi50jN0,iv:Ps9sfhSVUy8jDJbWFwdRHXGe+89Boj/CG6bCxEYpJpQ=,tag:xWbn7fob186Wjtljq3ahrg==,type:str]
    dbUser: ENC[AES256_GCM,data:kySNhW2EagG5mUDLcA==,iv:kNUAfz3ZkzW5x7uFn0Op7Iff0tENKqc28+jXLPXCIdU=,tag:Uequ6Q0+5u/2GsZqReZHdA==,type:str]
    dbPassword: ENC[AES256_GCM,data:DdQw9eHORDTXkKR1sXsTV2c=,iv:kJDp7qCLl/vi/QLs3XR6PJk6Uv1xySY7DmyBBgw3Efo=,tag:LaDCLNdipKAlFxGzJA7Ebw==,type:str]
sops:
    age:
        - recipient: age1dwzvf8mj4rgvacakeecghshlyqkv873e70azfhpstvzpfj9v0uws8eqgwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVjJneTFDamxiMHYzYmpN
            Q1FjaEVvMXlJWk9vYmQrUUprL2EvcmpJWFVvClBEbkpFVUtveUxYSnJKa1poY2RL
            OERIS2NNeHdndE1xZlpnUXp5UUZaZEkKLS0tIHVPT1Q2dnUrdWVKN1dZdElzUEVk
            TmNBZ1BkbkNmdFNjc3NNRSt3cGw4UjQKo+CSIx1dyuFEvS2DVp+PlFPfArwHlRho
            nhhb4NPWiuG2OtSzkCN+L0IpBdEOJC4yvJkUBYosB6m2neGdijicPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T00:50:19Z"
    mac: ENC[AES256_GCM,data:T6edKOueWAr3Pj3DDt+x3Vp6dKOF8RhFvPL68z3VASdswsphxzguN6x885qAz5mNfDqH7v71MfcAerYrmFcWD4whSKqEjjqQuqSnNR0QyNSsipY0rQIKyD0n/gdU4CrggAIf+Euu7Rztrv87Coixe7xyZO2bOuz4uRTpCwo8VEg=,iv:UPfBS2D4iJrLFeWta4NjN7YrAE6n0XJcduMg0rMWMsg=,tag:5SZAvm2ZKWCUZOcfTZcRLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
