secret:
    dbName: ENC[AES256_GCM,data:n4uYeOMdS2EJ/c0=,iv:y8DznEIUaQTpH3eIn0dDjmmIaS7nAaAyfsOvcb9vSiA=,tag:jZC1f8Di8SCJlAYcR7frJA==,type:str]
    dbUser: ENC[AES256_GCM,data:ySspoQ==,iv:0HBE31I6S9Cn9iff7C1v0Un0bLvPEVkNXShY0f/LZNs=,tag:bMOYXEcFA+t8XT3mupztsA==,type:str]
    dbPassword: ENC[AES256_GCM,data:U45DocUSHXA=,iv:1NBMvGydREWCf2e7PbmayeEiSqa/tsVWpi7z1GKnf9s=,tag:+oZZ3er1WwgJw7/tBL+zyw==,type:str]
sops:
    age:
        - recipient: age1a4f6hu2ly5mkda56jj8juep8w4mzluw2mc70ek5evkqvdztenyjqm7cykc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVzVSY0RZbERad0Y2Znc0
            cXZzbE9RUzZCcURKNWNlYmNHRE02UUZvcEJZClJoRjlXV25OUTlGdTI3ZWppRzVr
            SlNsQVkwM2ZkTXRxaVFrYmUzUWloV0kKLS0tIFh2bjVRRi8rNzVRWG1wWGJWQVFr
            TGs2U2ZYMWU2eEdLZXp4OW9yQnBGeU0KDcQvUwLr93r0K5e0H5D5n7N9lZnpnZUU
            CKCTO2+QkgsLMLtSr8/at/UPMfbo2CGR5RvKSMlBBD9pfkeJpoE06g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T05:19:49Z"
    mac: ENC[AES256_GCM,data:SNtTkBDmm1hPJcN1+xi+22giyV91ybjwJ+F/d1IGxO4tcAcayYvnzHZoscwqK2HY81v9OHX67Bg1eoMB2UXCDE55ZW0UrESP0tqewEO2shlYFrrXsMpF2XKzwegD3AJr2P3KxhlDZonrQTapKk2LnBC4RpnoL4o4USca2tdHjnQ=,iv:Krt+MwJkAeDtQ8nSCvTZnRUWxOY6OfAJvwYkpA2v8FI=,tag:dqNli8ohc3YFNkJwjqKOlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
